name: build and release

on:
  workflow_dispatch:  # 响应外部触发器
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        type: string

jobs:
  build-release:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ inputs.tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        echo "will build $TAG"
        ./build.sh "$TAG"
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.tag }}
        files: |
          *.deb
          Packages
          Release